version: '3.6'

services:
  BCFD:
    restart: always
    image: simonloudev/bcfd_web
    container_name: 'bcfd'
    volumes:
      - bcfd_filestorage:/usr/share/nginx/bcfd/storage
    environment:
      - VIRTUAL_HOST=bcfd.simon-lou.com
      - VIRTUAL_PORT=80
    expose:
      - 80

volumes:
  bcfd_filestorage:

networks:
  default:
    external:
      name: nginx-proxy
